VERSION: "0.5.3"
LANGUAGE: "en"
KEY:
  TEA: -1
  CARROT: -1
  BOTTOM_RODS: [1, 2, 3]
  COFFEE: 4
  DIGGING_TOOL: 5
  ALCOHOL: 6
  MAIN_ROD: 1
  SPOD_ROD: 7
  QUIT: "CTRL-C"
  PAUSE: "g"
  FRICTION_BRAKE_RESET: "g"
  FRICTION_BRAKE_QUIT: "h"
  MOVE_PAUSE: "w"
  MOVE_QUIT: "s"
STAT:
  ENERGY_THRESHOLD: 0.74
  HUNGER_THRESHOLD: 0.5
  COMFORT_THRESHOLD: 0.51
  TEA_DRINK_DELAY: 300
  COFFEE_LIMIT: 10
  COFFEE_PER_DRINK: 1
  ALCOHOL_DRINK_DELAY: 900
  ALCOHOL_PER_DRINK: 1
BOT:
  LAUNCH_OPTIONS: ""
  SMTP_VERIFICATION: true
  SNAG_DETECTION: true
  SPOOLING_DETECTION: true
  SPOOL_CONFIDENCE: 0.98
  RANDOM_CAST_PROBABILITY: 0.25
  SPOD_ROD_RECAST_DELAY: 1800
  LURE_CHANGE_DELAY: 1800
  PAUSE_DELAY: 1800
  PAUSE_DURATION: 600
  CLICK_LOCK: false
  KEEPNET:
    CAPACITY: 100
    SCREENSHOT_TAGS: ["yellow", "blue"]
    BYPASS_TAGS: ["yellow", "blue"]
    BLACKLIST: []
    WHITELIST: ["mackerel", "saithe", "herring", "squid", "scallop", "mussel"]
    KEEP_TAGS: ["green", "yellow", "blue", "purple", "pink"]
  NOTIFICATION:
    EMAIL: "email@example.com"
    PASSWORD: "password"
    SMTP_SERVER: "smtp.gmail.com"
    MIAO_CODE: ""
    DISCORD_WEBHOOK_URL: ""
    TELEGRAM_BOT_TOKEN: ""
    TELEGRAM_CHAT_ID: -1
  FRICTION_BRAKE:
    INITIAL: 29
    MAX: 30
    START_DELAY: 2.0
    INCREASE_DELAY: 1.0
    DECREASE_DELAY: 1.0
    SENSITIVITY: "high"
CRAFT:
  LAUNCH_OPTIONS: ""
MOVE:
  LAUNCH_OPTIONS: ""
HARVEST:
  LAUNCH_OPTIONS: ""
  POWER_SAVING: false
  CHECK_DELAY: 32
FRICTION_BRAKE:
  LAUNCH_OPTIONS: ""
  INITIAL: 29
  MAX: 30
  START_DELAY: 2.0
  INCREASE_DELAY: 1.0
  DECREASE_DELAY: 1.0
  SENSITIVITY: "high"
PROFILE:
  SPIN:
    DESCRIPTION: "Default spin fishing profile."
    LAUNCH_OPTIONS: ""
    MODE: "spin"
    TYPE: "normal"
    CAST_POWER_LEVEL: 5.0
    CAST_DELAY: 6.0
    TIGHTEN_DURATION: 0.0
    RETRIEVAL_DURATION: 0.0
    RETRIEVAL_DELAY: 0.0
    RETRIEVAL_TIMEOUT: 256.0
    PRE_ACCELERATION: false
    POST_ACCELERATION: false
  SPIN_WITH_PAUSE:
    DESCRIPTION: "Spin fishing with short pauses."
    LAUNCH_OPTIONS: ""
    MODE: "spin"
    CAST_POWER_LEVEL: 5.0
    CAST_DELAY: 6.0
    TIGHTEN_DURATION: 1.0
    RETRIEVAL_DURATION: 1.0
    RETRIEVAL_DELAY: 3.0
    RETRIEVAL_TIMEOUT: 256.0
    PRE_ACCELERATION: false
    POST_ACCELERATION: false
    TYPE: "pause"
  SPIN_WITH_LIFT:
    DESCRIPTION: "Spin fishing with short lifts."
    LAUNCH_OPTIONS: ""
    MODE: "spin"
    CAST_POWER_LEVEL: 5.0
    CAST_DELAY: 6.0
    TIGHTEN_DURATION: 0.0
    RETRIEVAL_DURATION: 1.0
    RETRIEVAL_DELAY: 1.0
    RETRIEVAL_TIMEOUT: 256.0
    PRE_ACCELERATION: false
    POST_ACCELERATION: false
    TYPE: "lift"
  BOTTOM:
    DESCRIPTION: "Default bottom fishing."
    LAUNCH_OPTIONS: ""
    MODE: "bottom"
    CAST_POWER_LEVEL: 5.0
    CAST_DELAY: 4.0
    POST_ACCELERATION: false
    CHECK_DELAY: 16.0
    CHECK_MISS_LIMIT: 16
    PUT_DOWN_DELAY: 2.0
    RANDOM_ROD_SELECTION: true
  PIRK:
    DESCRIPTION: "Default marine fishing, strong pirking at the bottom layer."
    LAUNCH_OPTIONS: ""
    MODE: "pirk"
    CAST_POWER_LEVEL: 1.0
    CAST_DELAY: 4.0
    SINK_TIMEOUT: 60.0
    TIGHTEN_DURATION: 1.0
    DEPTH_ADJUST_DELAY: 4.0
    DEPTH_ADJUST_DURATION: 1.0
    CTRL: false
    SHIFT: false
    PIRK_DURATION: 0.9
    PIRK_DELAY: 2.0
    PIRK_TIMEOUT: 32.0
    PIRK_RETRIEVAL: false
    HOOK_DELAY: 0.5
    POST_ACCELERATION: true
  PIRK_WITH_RETRIEVAL:
    DESCRIPTION: "Marine fishing, pirking while retrieving the fishing line."
    LAUNCH_OPTIONS: ""
    MODE: "pirk"
    CAST_POWER_LEVEL: 1.0
    CAST_DELAY: 4.0
    SINK_TIMEOUT: 60.0
    TIGHTEN_DURATION: 1.0
    DEPTH_ADJUST_DELAY: 0.0
    DEPTH_ADJUST_DURATION: 1.0
    CTRL: false
    SHIFT: false
    PIRK_DURATION: 0.5
    PIRK_DELAY: 2.0
    PIRK_TIMEOUT: 32.0
    PIRK_RETRIEVAL: true
    HOOK_DELAY: 0.5
    POST_ACCELERATION: true
  WACKY_RIG:
    DESCRIPTION: "Pirking at the bottom layer at Ladoga Archipelago using wacky rig."
    LAUNCH_OPTIONS: ""
    MODE: "pirk"
    CAST_POWER_LEVEL: 1.0
    CAST_DELAY: 4.0
    SINK_TIMEOUT: 45.0
    TIGHTEN_DURATION: 1.0
    DEPTH_ADJUST_DELAY: 4.0
    DEPTH_ADJUST_DURATION: 1.0
    CTRL: false
    SHIFT: false
    PIRK_DURATION: 1.5
    PIRK_DELAY: 4.0
    PIRK_TIMEOUT: 32.0
    PIRK_RETRIEVAL: false
    HOOK_DELAY: 0.5
    POST_ACCELERATION: true
  ELEVATOR:
    DESCRIPTION: "A marine fishing profile for elevator while fishing/trolling that recast the rod after timed out."
    LAUNCH_OPTIONS: ""
    MODE: "elevator"
    CAST_POWER_LEVEL: 1.0
    CAST_DELAY: 4.0
    SINK_TIMEOUT: 60.0
    TIGHTEN_DURATION: 1.0
    ELEVATE_DURATION: 4.0
    ELEVATE_DELAY: 4.0
    ELEVATE_TIMEOUT: 40.0
    DROP: false
    HOOK_DELAY: 0.5
    POST_ACCELERATION: true
  ELEVATOR_WITH_DROP:
    DESCRIPTION: "A marine fishing profile for elevator while fishing/trolling that lock/unlock the reel to drop the lure after timed out."
    LAUNCH_OPTIONS: ""
    MODE: "elevator"
    CAST_POWER_LEVEL: 1.0
    CAST_DELAY: 4.0
    SINK_TIMEOUT: 60.0
    TIGHTEN_DURATION: 1.0
    ELEVATE_DURATION: 4.0
    ELEVATE_DELAY: 4.0
    ELEVATE_TIMEOUT: 40.0
    DROP: true
    HOOK_DELAY: 0.5
    POST_ACCELERATION: true
  TELESCOPIC:
    DESCRIPTION: "Default float fishing profile for telescopic rod."
    LAUNCH_OPTIONS: ""
    MODE: "telescopic"
    CAST_POWER_LEVEL: 5.0
    CAST_DELAY: 4.0
    FLOAT_SENSITIVITY: 0.68
    CHECK_DELAY: 1.0
    PULL_DELAY: 0.5
    DRIFT_TIMEOUT: 4096.0
    CAMERA_SHAPE: "square"
  BOLOGNESE:
    DESCRIPTION: "Default float fishing profile for bolognese rod."
    LAUNCH_OPTIONS: ""
    MODE: "bolognese"
    CAST_POWER_LEVEL: 5.0
    CAST_DELAY: 4.0
    FLOAT_SENSITIVITY: 0.68
    CHECK_DELAY: 1.0
    PULL_DELAY: 0.5
    DRIFT_TIMEOUT: 64.0
    CAMERA_SHAPE: "square"
    POST_ACCELERATION: false
  MATCH:
    DESCRIPTION: "Default float fishing profile for match rod."
    LAUNCH_OPTIONS: ""
    MODE: "bolognese"
    CAST_POWER_LEVEL: 5.0
    CAST_DELAY: 4.0
    FLOAT_SENSITIVITY: 0.68
    CHECK_DELAY: 1.0
    PULL_DELAY: 0.0
    DRIFT_TIMEOUT: 64.0
    CAMERA_SHAPE: "square"
    POST_ACCELERATION: false

  Copper Lake, 61:53, F1:
    DESCRIPTION: "c12, ~90% cast power."
    LAUNCH_OPTIONS: ""
    MODE: "bottom"
    CAST_POWER_LEVEL: 3.5
    CAST_DELAY: 4.0
    POST_ACCELERATION: false
    CHECK_DELAY: 16.0
    CHECK_MISS_LIMIT: 16
    PUT_DOWN_DELAY: 2.0

  Norwegian Sea, 175m, Strong pirking in bottom layer:
    DESCRIPTION: "Strong pirking at bottom layer, 175m."
    LAUNCH_OPTIONS: ""
    MODE: "pirk"
    CAST_POWER_LEVEL: 1.0
    CAST_DELAY: 4.0
    SINK_TIMEOUT: 140.0
    TIGHTEN_DURATION: 2.0
    DEPTH_ADJUST_DELAY: 4.0
    DEPTH_ADJUST_DURATION: 2.0
    CTRL: false
    SHIFT: false
    PIRK_DURATION: 0.8
    PIRK_DELAY: 2.2
    PIRK_TIMEOUT: 60.0
    PIRK_RETRIEVAL: false
    HOOK_DELAY: 0.5
    POST_ACCELERATION: true

  Norwegian Sea, 144m, Movement in bottom layer:
    DESCRIPTION: "Movement at the bottom layer."
    LAUNCH_OPTIONS: ""
    MODE: "pirk"
    CAST_POWER_LEVEL: 1.0
    CAST_DELAY: 4.0
    SINK_TIMEOUT: 80.0
    TIGHTEN_DURATION: 2.0
    DEPTH_ADJUST_DELAY: 4.0
    DEPTH_ADJUST_DURATION: 2.0
    CTRL: false
    SHIFT: false
    PIRK_DURATION: 0.0
    PIRK_DELAY: 0.0
    PIRK_TIMEOUT: 60.0
    PIRK_RETRIEVAL: false
    HOOK_DELAY: 0.5
    POST_ACCELERATION: True

  Old Burg Lake, 21:67, Black Carp:
    DESCRIPTION: "c17, 50% cast power."
    LAUNCH_OPTIONS: ""
    MODE: "bottom"
    CAST_POWER_LEVEL: 3.0
    CAST_DELAY: 4.0
    POST_ACCELERATION: false
    CHECK_DELAY: 64.0
    CHECK_MISS_LIMIT: 16
    PUT_DOWN_DELAY: 2.0
    RANDOM_ROD_SELECTION: true

  Ladoga Lake, 73:55, Ludoga Whitefish:
    DESCRIPTION: "c10, depth 150cm, full cast power."
    LAUNCH_OPTIONS: ""
    MODE: "bolognese"
    CAST_POWER_LEVEL: 5.0
    CAST_DELAY: 4.0
    FLOAT_SENSITIVITY: 0.68
    CHECK_DELAY: 1.0
    PULL_DELAY: 2.0
    DRIFT_TIMEOUT: 128.0
    CAMERA_SHAPE: "square"
    POST_ACCELERATION: true

  Norwegian Sea, 34m, Strong pirking, Atlantic Saury:
    DESCRIPTION: "Strong pirking at 34m, c15"
    MODE: "pirk"
    LAUNCH_OPTIONS: ""
    CAST_POWER_LEVEL: 1.0
    CAST_DELAY: 4.0
    SINK_TIMEOUT: 12.0
    TIGHTEN_DURATION: 0.1
    DEPTH_ADJUST_DELAY: 2.0
    DEPTH_ADJUST_DURATION: 1.0
    CTRL: false
    SHIFT: false
    PIRK_DURATION: 1.5
    PIRK_DELAY: 2.0
    PIRK_TIMEOUT: 32.0
    PIRK_RETRIEVAL: false
    HOOK_DELAY: 0.5
    POST_ACCELERATION: true

  Elk Lake, Jig step:
    DESCRIPTION: ""
    LAUNCH_OPTIONS: ""
    MODE: "spin"
    CAST_POWER_LEVEL: 5.0
    CAST_DELAY: 6.0
    TIGHTEN_DURATION: 0.5
    RETRIEVAL_DURATION: 0.5
    RETRIEVAL_DELAY: 2.0
    RETRIEVAL_TIMEOUT: 256.0
    PRE_ACCELERATION: false
    POST_ACCELERATION: true
    TYPE: "pause"

  Copper Lake, :
    DESCRIPTION: ""
    LAUNCH_OPTIONS: ""
    MODE: "bottom"
    CAST_POWER_LEVEL: 4.0
    CAST_DELAY: 4.0
    POST_ACCELERATION: false
    CHECK_DELAY: 64.0
    CHECK_MISS_LIMIT: 16
    PUT_DOWN_DELAY: 2.0


  Norwegian Sea, 120m, Movement in bottom layer:
    DESCRIPTION: ""
    LAUNCH_OPTIONS: "-rctDdR -GR -FB -BL"
    MODE: "pirk"
    CAST_POWER_LEVEL: 1.0
    CAST_DELAY: 4.0
    SINK_TIMEOUT: 140.0
    TIGHTEN_DURATION: 3.0
    DEPTH_ADJUST_DELAY: 4.0
    DEPTH_ADJUST_DURATION: 2.0
    CTRL: false
    SHIFT: false
    PIRK_DURATION: 0.0
    PIRK_DELAY: 0.0
    PIRK_TIMEOUT: 32.0
    PIRK_RETRIEVAL: false
    HOOK_DELAY: 0.5
    POST_ACCELERATION: true

  Norwegian Sea, 88m, Strong pirking in bottom layer:
    DESCRIPTION: ""
    LAUNCH_OPTIONS: "-rctDdR -GR -FB -BL"
    MODE: "pirk"
    CAST_POWER_LEVEL: 1.0
    CAST_DELAY: 4.0
    SINK_TIMEOUT: 60.0
    TIGHTEN_DURATION: 3.0
    DEPTH_ADJUST_DELAY: 4.0
    DEPTH_ADJUST_DURATION: 2.0
    CTRL: false
    SHIFT: false
    PIRK_DURATION: 0.5
    PIRK_DELAY: 1.7
    PIRK_TIMEOUT: 32.0
    PIRK_RETRIEVAL: false
    HOOK_DELAY: 0.5
    POST_ACCELERATION: true

  Kuori Lake, 92:100?, Twitching:
    DESCRIPTION: ""
    LAUNCH_OPTIONS: "-rctDdR"
    MODE: "spin"
    CAST_POWER_LEVEL: 5.0
    CAST_DELAY: 6.0
    TIGHTEN_DURATION: 0.2
    RETRIEVAL_DURATION: 0.3
    RETRIEVAL_DELAY: 1.0
    RETRIEVAL_TIMEOUT: 256.0
    PRE_ACCELERATION: false
    POST_ACCELERATION: true
    TYPE: "pause"


  Norwegian Sea, 41m, Movement in bottom layer:
    DESCRIPTION: ""
    LAUNCH_OPTIONS: "-rctDdR -GR -BL"
    MODE: "pirk"
    CAST_POWER_LEVEL: 1.0
    CAST_DELAY: 4.0
    SINK_TIMEOUT: 40.0
    TIGHTEN_DURATION: 2.0
    DEPTH_ADJUST_DELAY: 2.0
    DEPTH_ADJUST_DURATION: 2.0
    CTRL: false
    SHIFT: false
    PIRK_DURATION: 0.0
    PIRK_DELAY: 0.0
    PIRK_TIMEOUT: 32.0
    PIRK_RETRIEVAL: false
    HOOK_DELAY: 0.5
    POST_ACCELERATION: true

  YAMA_WALK_THE_DOG:
    LAUNCH_OPTIONS: "-rcmR"
    MODE: "spin"
    CAST_POWER_LEVEL: 5.0
    CAST_DELAY: 6.0
    TIGHTEN_DURATION: 0.1
    RETRIEVAL_TIMEOUT: 256.0
    RETRIEVAL_DURATION: 0.55
    RETRIEVAL_DELAY: 1.5
    PRE_ACCELERATION: False
    POST_ACCELERATION: false
    TYPE: "pause"


  BEAR_C17:
    MODE: "bottom"
    CAST_POWER_LEVEL: 2.5
    CAST_DELAY: 4.0
    POST_ACCELERATION: false
    CHECK_DELAY: 32.0
    CHECK_MISS_LIMIT: 10

  COPPER_C18:
    MODE: "bottom"
    CAST_POWER_LEVEL: 4.0
    CAST_DELAY: 4.0
    POST_ACCELERATION: false
    CHECK_DELAY: 64.0
    CHECK_MISS_LIMIT: 10

  COPPER_C31:
    MODE: "bottom"
    CAST_POWER_LEVEL: 4.0
    CAST_DELAY: 4.0
    POST_ACCELERATION: false
    CHECK_DELAY: 32.0
    CHECK_MISS_LIMIT: 10

  COPPER_C6:
    MODE: "bottom"
    CAST_POWER_LEVEL: 3.0
    CAST_DELAY: 4.0
    POST_ACCELERATION: false
    CHECK_DELAY: 16.0
    CHECK_MISS_LIMIT: 10

  AMBER_TROPHY:
      MODE: "bottom"
      CAST_POWER_LEVEL: 5.0
      CAST_DELAY: 4.0
      POST_ACCELERATION: false
      CHECK_DELAY: 64.0
      CHECK_MISS_LIMIT: 10

  PIRK_80:
    MODE: "pirk"
    LAUNCH_OPTIONS: ""
    CAST_POWER_LEVEL: 1.0
    CAST_DELAY: 4.0
    SINK_TIMEOUT: 60.0
    TIGHTEN_DURATION: 2.0
    DEPTH_ADJUST_DELAY: 4.0
    DEPTH_ADJUST_DURATION: 1.0
    CTRL: false
    SHIFT: false
    PIRK_DURATION: 0.5
    PIRK_DELAY: 2.0
    PIRK_TIMEOUT: 128.0
    PIRK_RETRIEVAL: false
    HOOK_DELAY: 0.5
    POST_ACCELERATION: true

  ELK:
    MODE: "bolognese"
    LAUNCH_OPTIONS: ""
    CAST_POWER_LEVEL: 5.0
    CAST_DELAY: 4.0
    FLOAT_SENSITIVITY: 0.68
    CHECK_DELAY: 1.0
    PULL_DELAY: 0.0
    DRIFT_TIMEOUT: 100.0
    CAMERA_SHAPE: "square"
    POST_ACCELERATION: false