VERSION: "0.5.3"
LANGUAGE: "en"
KEY:
  TEA: -1
  CARROT: -1
  BOTTOM_RODS: [1, 2, 3]
  COFFEE: 4
  DIGGING_TOOL: 5
  ALCOHOL: 6
  MAIN_ROD: 1
  SPOD_ROD: 7
  QUIT: "CTRL-C"
  PAUSE: "g"
  FRICTION_BRAKE_RESET: "g"
  FRICTION_BRAKE_QUIT: "h"
  MOVE_PAUSE: "w"
  MOVE_QUIT: "s"
STAT:
  ENERGY_THRESHOLD: 0.74
  HUNGER_THRESHOLD: 0.5
  COMFORT_THRESHOLD: 0.51
  TEA_DRINK_DELAY: 300
  COFFEE_LIMIT: 10
  COFFEE_PER_DRINK: 1
  ALCOHOL_DRINK_DELAY: 900
  ALCOHOL_PER_DRINK: 1
BOT:
  LAUNCH_OPTIONS: ""
  SMTP_VERIFICATION: true
  SNAG_DETECTION: true
  SPOOLING_DETECTION: true
  SPOOL_CONFIDENCE: 0.98
  RANDOM_CAST_PROBABILITY: 0.25
  SPOD_ROD_RECAST_DELAY: 1800
  LURE_CHANGE_DELAY: 1800
  PAUSE_DELAY: 1800
  PAUSE_DURATION: 600
  CLICK_LOCK: false
  KEEPNET:
    CAPACITY: 100
    SCREENSHOT_TAGS: [yellow, blue]
    BYPASS_TAGS: [yellow, blue]
    WHITELIST: [mackerel, saithe, herring, squid, scallop, mussel]
    BLACKLIST: []
    KEEP_TAGS: [green, yellow, blue, purple, pink]
  NOTIFICATION:
    EMAIL: "email@example.com"
    PASSWORD: "password"
    SMTP_SERVER: "smtp.gmail.com"
    MIAO_CODE: ""
    DISCORD_WEBHOOK_URL: ""
    TELEGRAM_BOT_TOKEN: ""
    TELEGRAM_CHAT_ID: -1
  FRICTION_BRAKE:
    INITIAL: 29
    MAX: 30
    START_DELAY: 2.0
    INCREASE_DELAY: 1.0
    DECREASE_DELAY: 1.0
    SENSITIVITY: "high"
CRAFT:
  LAUNCH_OPTIONS: ""
MOVE:
  LAUNCH_OPTIONS: ""
HARVEST:
  LAUNCH_OPTIONS: ""
  POWER_SAVING: false
  CHECK_DELAY: 32
FRICTION_BRAKE:
  LAUNCH_OPTIONS: ""
  INITIAL: 29
  MAX: 30
  START_DELAY: 2.0
  INCREASE_DELAY: 1.0
  DECREASE_DELAY: 1.0
  SENSITIVITY: "high"
PROFILE:
  SPIN:
    DESCRIPTION: "Default spin fishing profile."
    MODE: "spin"
    TYPE: "normal"
    LAUNCH_OPTIONS: ""
    CAST_POWER_LEVEL: 5.0
    CAST_DELAY: 6.0
    TIGHTEN_DURATION: 0.0
    RETRIEVAL_DURATION: 0.0
    RETRIEVAL_DELAY: 0.0
    RETRIEVAL_TIMEOUT: 256.0
    PRE_ACCELERATION: false
    POST_ACCELERATION: false
  SPIN_WITH_PAUSE:
    DESCRIPTION: "Spin fishing with short pauses."
    MODE: "spin"
    TYPE: "pause"
    LAUNCH_OPTIONS: ""
    CAST_POWER_LEVEL: 5.0
    CAST_DELAY: 6.0
    TIGHTEN_DURATION: 1.0
    RETRIEVAL_DURATION: 1.0
    RETRIEVAL_DELAY: 3.0
    RETRIEVAL_TIMEOUT: 256.0
    PRE_ACCELERATION: false
    POST_ACCELERATION: false
  SPIN_WITH_LIFT:
    DESCRIPTION: "Spin fishing with short lifts."
    MODE: "spin"
    TYPE: "lift"
    LAUNCH_OPTIONS: ""
    CAST_POWER_LEVEL: 5.0
    CAST_DELAY: 6.0
    TIGHTEN_DURATION: 0.0
    RETRIEVAL_DURATION: 1.0
    RETRIEVAL_DELAY: 1.0
    RETRIEVAL_TIMEOUT: 256.0
    PRE_ACCELERATION: false
    POST_ACCELERATION: false
  BOTTOM:
    DESCRIPTION: "Default bottom fishing profile."
    MODE: "bottom"
    LAUNCH_OPTIONS: ""
    CAST_POWER_LEVEL: 5.0
    CAST_DELAY: 4.0
    POST_ACCELERATION: false
    CHECK_DELAY: 32.0
    CHECK_MISS_LIMIT: 16
    PUT_DOWN_DELAY: 0.0
    RANDOM_ROD_SELECTION: true
  PIRK:
    DESCRIPTION: "A marine fishing profile that perform pirking at the bottom layer
      for 34/41 holes in Norwegian Sea."
    MODE: "pirk"
    LAUNCH_OPTIONS: ""
    CAST_POWER_LEVEL: 1.0
    CAST_DELAY: 4.0
    SINK_TIMEOUT: 60.0
    TIGHTEN_DURATION: 1.0
    DEPTH_ADJUST_DELAY: 4.0
    DEPTH_ADJUST_DURATION: 1.0
    CTRL: false
    SHIFT: false
    PIRK_DURATION: 0.5
    PIRK_DELAY: 2.0
    PIRK_TIMEOUT: 32.0
    PIRK_RETRIEVAL: false
    HOOK_DELAY: 0.5
    POST_ACCELERATION: false
  PIRK_WITH_RETRIEVAL:
    DESCRIPTION: "A marine fishing profile that retrieves the fishing line while parking."
    MODE: "pirk"
    LAUNCH_OPTIONS: ""
    CAST_POWER_LEVEL: 1.0
    CAST_DELAY: 4.0
    SINK_TIMEOUT: 60.0
    TIGHTEN_DURATION: 1.0
    DEPTH_ADJUST_DELAY: 0.0
    DEPTH_ADJUST_DURATION: 1.0
    CTRL: false
    SHIFT: false
    PIRK_DURATION: 0.5
    PIRK_DELAY: 2.0
    PIRK_TIMEOUT: 32.0
    PIRK_RETRIEVAL: true
    HOOK_DELAY: 0.5
    POST_ACCELERATION: false
  WACKY_RIG:
    DESCRIPTION: "A variation of marine fishing profile for pirking at the bottom layer
      at Ladoga Archipelago using wacky rig."
    MODE: "pirk"
    LAUNCH_OPTIONS: ""
    CAST_POWER_LEVEL: 1.0
    CAST_DELAY: 4.0
    SINK_TIMEOUT: 45.0
    TIGHTEN_DURATION: 1.0
    DEPTH_ADJUST_DELAY: 4.0
    DEPTH_ADJUST_DURATION: 1.0
    CTRL: false
    SHIFT: false
    PIRK_DURATION: 1.5
    PIRK_DELAY: 4.0
    PIRK_TIMEOUT: 32.0
    PIRK_RETRIEVAL: false
    HOOK_DELAY: 0.5
    POST_ACCELERATION: false
  ELEVATOR:
    DESCRIPTION: "A marine fishing profile for elevator while fishing/trolling."
    MODE: "elevator"
    LAUNCH_OPTIONS: ""
    CAST_POWER_LEVEL: 1.0
    CAST_DELAY: 4.0
    SINK_TIMEOUT: 60.0
    TIGHTEN_DURATION: 1.0
    ELEVATE_DURATION: 4.0
    ELEVATE_DELAY: 4.0
    ELEVATE_TIMEOUT: 40.0
    DROP: false
    HOOK_DELAY: 0.5
    POST_ACCELERATION: false
  ELEVATOR_WITH_DROP:
    MODE: "elevator"
    LAUNCH_OPTIONS: ""
    CAST_POWER_LEVEL: 1.0
    CAST_DELAY: 4.0
    SINK_TIMEOUT: 60.0
    TIGHTEN_DURATION: 1.0
    ELEVATE_DURATION: 4.0
    ELEVATE_DELAY: 4.0
    ELEVATE_TIMEOUT: 40.0
    DROP: true
    HOOK_DELAY: 0.5
    POST_ACCELERATION: false
  TELESCOPIC:
    DESCRIPTION: "Default float fishing profile for telescopic rod."
    MODE: "telescopic"
    LAUNCH_OPTIONS: ""
    CAST_POWER_LEVEL: 5.0
    CAST_DELAY: 4.0
    FLOAT_SENSITIVITY: 0.68
    CHECK_DELAY: 1.0
    PULL_DELAY: 0.5
    DRIFT_TIMEOUT: 16.0
    CAMERA_SHAPE: "square"
  BOLOGNESE:
    DESCRIPTION: "Default float fishing profile for bolognese rod."
    MODE: "bolognese"
    LAUNCH_OPTIONS: ""
    CAST_POWER_LEVEL: 5.0
    CAST_DELAY: 4.0
    FLOAT_SENSITIVITY: 0.68
    CHECK_DELAY: 1.0
    PULL_DELAY: 0.5
    DRIFT_TIMEOUT: 32.0
    CAMERA_SHAPE: "square"
    POST_ACCELERATION: false
  MATCH:
    DESCRIPTION: "Default float fishing profile for match rod."
    MODE: "bolognese"
    LAUNCH_OPTIONS: ""
    CAST_POWER_LEVEL: 5.0
    CAST_DELAY: 4.0
    FLOAT_SENSITIVITY: 0.68
    CHECK_DELAY: 1.0
    PULL_DELAY: 0.0
    DRIFT_TIMEOUT: 64.0
    CAMERA_SHAPE: "square"
    POST_ACCELERATION: false